spring.config.activate.on-profile: default, local

spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      file: modules/docker/docker-compose-local.yml

---
spring.config.activate.on-profile: test, dev, stage, prod

spring:
  docker:
    compose:
      enabled: false
